'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RandomMakerv6PP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Bag_吃剩的东西_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_吃剩的东西_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Bag_弱点保险_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_弱点保险_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Bag_生命宝珠_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_生命宝珠_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Bag_精灵球_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_精灵球_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property Bag_讲究围巾_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_讲究围巾_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property bton1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bton1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property CELEBI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CELEBI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property DialogDP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DialogDP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property EDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property hgssdialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hgssdialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property LATITWINS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LATITWINS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property LATITWINS2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LATITWINS2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property LDING() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LDING", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property MELOETTA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MELOETTA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ORASDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ORASDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property PG0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PG0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property PG1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PG1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property PG2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PG2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property PG3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PG3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property PtDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PtDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property SINNOH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SINNOH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property STEENEE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STEENEE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 关闭() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("关闭", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 初次邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("初次邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 右箭头() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("右箭头", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 喜爱邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("喜爱邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 回复邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("回复邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 天空邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("天空邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 左箭头() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("左箭头", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 常规选项卡() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("常规选项卡", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 彩嵌邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("彩嵌邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 感谢邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("感谢邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 推荐邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("推荐邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 暴雪邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("暴雪邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 桥梁邮件Ｃ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桥梁邮件Ｃ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 桥梁邮件Ｈ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桥梁邮件Ｈ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 桥梁邮件Ｓ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桥梁邮件Ｓ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 桥梁邮件Ｖ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桥梁邮件Ｖ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 桥梁邮件Ｗ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("桥梁邮件Ｗ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 水蓝邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("水蓝邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 火焰邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("火焰邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 甜蜜邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("甜蜜邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 砖块邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("砖块邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 空间邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("空间邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 绽放邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("绽放邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 虚化右箭头() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("虚化右箭头", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 虚化左箭头() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("虚化左箭头", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 设置主界面() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("设置主界面", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 返回键() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("返回键", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 选定选项卡() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("选定选项卡", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 邀请邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("邀请邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 钢铁邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("钢铁邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 隧道邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("隧道邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property 青草邮件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("青草邮件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
